### ISSUE TITLE
Allow costs pp for event

### ISSUE THREAD

**Issue by dexbleeker** [DispuutHamers/webapp#321]
Zodat kosten van een (externe) activiteit kunnen worden aangegeven.

**Comment by koenjdejong** [comment]
Willen we dit nog? Ben het wel eens met Jacko, omdat de kosten vaak niet zeker zijn bij onze activiteiten

**Comment by dexbleeker** [comment]
Issue mag dicht van mij. Heb er zelf geen tijd voor momenteel en het is maar de vraag in hoeverre het gebruikt zou gaan worden.
