### ISSUE TITLE
The return of the Sunday ratio

### ISSUE THREAD

**Issue by koenjdejong** [DispuutHamers/webapp#451]
During the ALV it was brought up that bringing back a weekly mail of the Sunday ratio would be a good idea to raise attendance.

**Comment by dexbleeker** [comment]
I think you (or I?) misunderstood a little. The sunday ratio was always a value on the website, not a mailing. 

There was a comment however that the signup mailing was extended for lazy people like @LvanArkel, to give a little extra nudge to use the signup feature of the website and let people know whether they would join or not. That feature however was [never finished](https://github.com/DispuutHamers/webapp/pull/46).

**Comment by koenjdejong** [comment]
Check, ik zat idd fout
