### ISSUE TITLE
Automatic New Event Message

### ISSUE THREAD

**Issue by koenjdejong** [DispuutHamers/webapp#461]
Any new activity made that is not a normal Wednesday borrel, all active members will receive a message with title and description

**Comment by jackozi** [comment]
Waarschijnlijk moet er dan ook een toggle zijn om dit aan of uit te zetten in je account. We willen niet dat mensen het mail adres gaan blocken oid.

**Comment by koenjdejong** [comment]
Goede toevoeging idd
