### ISSUE TITLE
Description not visible for stickers

### ISSUE THREAD

**Issue by dexbleeker** [DispuutHamers/webapp#488]
This is the case in both the table for 'my stickers' and the map. In the past clicking a pin on the map yielded something like a popover with the description (if it existed).

**Comment by jackozi** [comment]
![Screenshot 2022-09-29 at 09 13 51](https://user-images.githubusercontent.com/2853450/192964631-69abbbcd-374a-4a7e-878c-6c0eaa3d4bb5.png)

Dit bedoel je. Dat werkt gewoon nog 😅

**Comment by dexbleeker** [comment]
Werkt alleen op mobiel niet dan? Lukt me hier niet iig

**Comment by jackozi** [comment]
Toch maar naar Safari dan 😂🤷‍♂️

**Comment by jackozi** [comment]
Is een on hover, denk dat je misschien ooit iets met klik in de Android app had gedaan.
