### ISSUE TITLE
Data validation when adding a sticker

### ISSUE THREAD

**Issue by LvanArkel** [DispuutHamers/webapp#585]
Adding a newline in the notes section of adding a sticker breaks the map when viewing all stickers.
The data should be validated to remove any newlines, or the notes field should be a single-line textfield so that adding newlines would not be possible.

**Comment by dexbleeker** [comment]
Of we moeten de kaart fixen? Ik begrijp niet waarom newlines niet zouden moeten kunnen. Wellicht gaan we in de toekomst de stickers nog op een andere manier weergeven (lijst oid), dan kan het zeker nuttig zijn om newlines te hebben wellicht?

Bovendien moet je anders ook alle oude stickers gaan aanpassen om de newlines eruit te halen, wat me ongewenst lijkt. Beter gewoon eruit strippen voor je het in de map duwt.
